name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/home/${{ secrets.USERNAME }}/lucamatei.eu-temp"
        script: |
          rm -rf /home/${{ secrets.USERNAME }}/lucamatei.eu
          mv /home/${{ secrets.USERNAME }}/lucamatei.eu-temp /home/${{ secrets.USERNAME }}/lucamatei.eu
          
          cd /home/${{ secrets.USERNAME }}/lucamatei.eu

          echo "SENDGRID_RECEIVER=${{ secrets.SENDGRID_RECEIVER }}" > .env
          echo "SENDGRID_SENDER=${{ secrets.SENDGRID_SENDER }}" >> .env
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env

          yarn install
          yarn build

          sudo systemctl restart lucamatei.eu
